version: '3.8'

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: commute_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
        
  dataprocessor:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-dataprocessor
    environment:
      ConnectionStrings__commutedb: Host=postgresql;Username=user;Password=password;Database=commutedb
      ConnectionStrings__messaging: amqp://user:password@rabbitmq:5672/
      DOTNET_ENVIRONMENT: Development
    depends_on:
      - rabbitmq
      - postgresql
  
  datafetcher:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-datafetcher
    environment:
      ConnectionStrings__messaging: amqp://user:password@rabbitmq:5672/
      GOOGLE_BASE_URL: http://maps:8080
      TRANSIT_BASE_URL: http://transit:8080
      DOTNET_ENVIRONMENT: Development
    depends_on:
      - rabbitmq
      - transit
      - maps
  
  apiservice:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-apiservice
    environment:
      ConnectionStrings__commutedb: Host=postgresql;Username=user;Password=password;Database=commutedb
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - postgresql
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-web
    command: /bin/bash
    depends_on:
      - apiservice
    environment:
      API_BASE_URL: http://apiservice:8080
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5015:8080"
  
  maps:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-maps
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  
  transit:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-transit
    environment:
      ASPNETCORE_ENVIRONMENT: Development

volumes:
  postgres-data:
  rabbitmq-data: